# Render deployment configuration
services:
  # Backend Web Service
  - type: web
    name: music-recommender-backend
    runtime: python
    env: python
    region: oregon
    buildCommand: pip install -r backend-web-service/requirements.txt
    startCommand: cd backend-web-service && sanic server:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    # Uncomment if you need auto-deploy
    # autoDeploy: true

